### ISSUE TITLE
Add README to all packages

### ISSUE THREAD

**Issue by demmm** [KaOS-Community-Packages/makemkv#1]
README is required for submission to KCP, please fix all your packages.
One more time, read the KCP Guide fully, follow all guidelines set there for you, including needed standards for the README.
As always for wrongly submitted packages you have 24-48 hours to correct, otherwise packages will be removed.

**Comment by demmm** [comment]
Still not following guidelines for README, correct all your packages according to the clearly set needs.

**Comment by timcowchip** [comment]
On Saturday, July 11, 2015 10:56:31 AM demmm wrote:
> Still not following guidelines for README, correct all your packages
> according to the clearly set needs.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/KaOS-Community-Packages/makemkv/issues/
1#issuecomment-120
> 648243
I've added url's for all and needed packages from KCP for gigolo and RSS-Guard 
didn't have a readme.md, so I added one. Is there anything I left out?

**Comment by demmm** [comment]
Seems complete now, thanks.  Closing the issue.
